# Generated by Django 4.1.2 on 2022-10-21 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_cart_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advuser',
            name='username',
        ),
        migrations.AddField(
            model_name='advuser',
            name='fio',
            field=models.CharField(default='Иван Иванов', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='advuser',
            name='email',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
